ALTER TABLE file
    ADD COLUMN IF NOT EXISTS storage_type VARCHAR(20) DEFAULT 'local',
    ADD COLUMN IF NOT EXISTS bucket_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS object_key TEXT,
    ADD COLUMN IF NOT EXISTS original_filename VARCHAR(255),
    ADD COLUMN IF NOT EXISTS file_size BIGINT,
    ADD COLUMN IF NOT EXISTS crs VARCHAR(100),
    ADD COLUMN IF NOT EXISTS bbox TEXT;

ALTER TABLE task_item
    ADD COLUMN IF NOT EXISTS file_id INTEGER;

ALTER TABLE model
    ADD COLUMN IF NOT EXISTS storage_type VARCHAR(20) DEFAULT 'local',
    ADD COLUMN IF NOT EXISTS bucket_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS object_key TEXT,
    ADD COLUMN IF NOT EXISTS file_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS original_filename VARCHAR(255);

ALTER TABLE sampleset
    ADD COLUMN IF NOT EXISTS export_object_key TEXT;
